### PR TITLE
Fix #58: update lifecycle-mapping-metadata.xml to support javac-with-…

### LINKED ISSUE #58: Annotation processing is not enabled with compilerId javac-with-errorprone
Annotation processing does not work with the maven-compiler-plugin if compilerId javac-with-errorprone is used.  m2e 1.8 (in Oxygen) supports this now so it would be good to have support in m2e-apt as well.  AFAIK all that is required is to add it to the lifecycleMappingMetadata.xml.

### PR DESCRIPTION
**Pull request by facboy**
…errorprone

compilerId.

### CODE REVIEW

**Comment by fbricon** [comment]
Can you please add some unit tests, like for https://github.com/jbosstools/m2e-apt/commit/7453155944c7621ac7738bf300a029a005dbd1ac and also [sign-off your commit](https://github.com/probot/dco#how-it-works)?

Thanks for your contribution!

**Comment by facboy** [comment]
i think this is ready to merge, can you take a look please?

**Comment by fbricon** [comment]
Thanks for your contribution @facboy !

**Comment by fbricon** [comment]
Waiting on the [builds to be fixed at Red Hat](https://issues.jboss.org/browse/JBIDE-25552), so that we can publish the new bits.

**Pull request merged**
